### ISSUE TITLE
The call to LeastSquaresMetaModelSelectionFactory should use default settings.

### ISSUE THREAD

**Issue by mbaudin47** [openturns/otsklearn#6]
At:

https://github.com/openturns/otsklearn/blob/master/otsklearn/otsklearn.py#L87

we see that the LARS and CorrectedLeaveOneOut algorithms are specifically set. Actually, these are the default values of the LeastSquaresMetaModelSelectionFactory () class. 

This is why we should rather use the statement:

    projectionStrategy = ot.LeastSquaresStrategy(ot.LeastSquaresMetaModelSelectionFactory())

This way, the default values are always used, which is a more robust approach, isn't it ?

**Comment by sofianehaddad** [comment]
@mbaudin47 or we might add a key parameter to handle the `fitting_algorithm`
